[package]
name = "sdq"
version = "0.1.0"
authors = ["Yana Agun Siswanto <yana.developer@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
quick-xml = "0.13.3"
rusqlite = "0.17.0"
